name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37.1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Start test.
        run: go test -race ./...